<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/session.php'; require_once __DIR__ . '/includes/helpers.php'; require_once __DIR__ . '/includes/auth.php'; require_once __DIR__ . '/includes/csrf.php'; require_once __DIR__ . '/includes/booking.php';
require_login();
$filters = ['sport_type' => trim((string) ($_GET['sport_type'] ?? '')), 'area_type' => trim((string) ($_GET['area_type'] ?? '')), 'max_price' => trim((string) ($_GET['max_price'] ?? ''))];
$resources = booking_resources($filters);
$selected = (int) ($_SESSION['booking']['resource_id'] ?? 0);
$map_resource_ids = ['tennis-a' => 1, 'tennis-b' => 2, 'multifunktionshalle' => 3, 'beachvolleyball' => 4, 'kleinfeld' => 5];
if (isset($_GET['anlage']) && isset($map_resource_ids[$_GET['anlage']])) {
	$selected = $map_resource_ids[$_GET['anlage']];
}
if ($_SERVER['REQUEST_METHOD'] === 'POST') { verify_csrf(); $resource_id = (int) ($_POST['resource_id'] ?? 0); $available = array_filter($resources, static fn (array $resource): bool => (int) $resource['id'] === $resource_id); if (!$available) { flash('danger', 'Bitte wählen Sie eine verfügbare Sportanlage.'); } else { $_SESSION['booking'] = ['resource_id' => $resource_id]; redirect('booking-step-2.php'); } }
$page_title = 'Sportanlage auswählen'; require __DIR__ . '/includes/header.php';
?><p class="step-indicator">Schritt 1 von 4</p><h1>Sportanlage auswählen</h1><p class="lead">Wählen Sie Ihren Lieblingsort am Standort Hauptstraße 1, Friedberg.</p>
<form method="get" class="row g-2 mb-4"><div class="col-md-4"><label class="form-label" for="sport_type">Sportart</label><select class="form-select" id="sport_type" name="sport_type"><option value="">Alle Sportarten</option><?php foreach (['Tennis', 'Hallenfussball', 'Beachvolleyball', 'Fussball'] as $sport): ?><option <?= $filters['sport_type'] === $sport ? 'selected' : '' ?>><?= e($sport) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label" for="area_type">Bereich</label><select class="form-select" id="area_type" name="area_type"><option value="">Innen und außen</option><option value="innen" <?= $filters['area_type'] === 'innen' ? 'selected' : '' ?>>Innen</option><option value="aussen" <?= $filters['area_type'] === 'aussen' ? 'selected' : '' ?>>Außen</option></select></div><div class="col-md-3"><label class="form-label" for="max_price">Maximalpreis</label><input class="form-control" id="max_price" name="max_price" type="number" min="0" step="0.01" value="<?= e($filters['max_price']) ?>"></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-outline-primary w-100" type="submit">Filtern</button></div></form>
<form method="post" id="resource-selection-form" data-area-filter="<?= e($filters['area_type']) ?>"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><div class="map-layout mb-4"><div class="map-selection"><h2 class="h4">Auswahl</h2><?php foreach ($resources as $resource): ?><label class="resource-card" data-resource-card="<?= (int) $resource['id'] ?>"><input class="form-check-input me-2" type="radio" name="resource_id" value="<?= (int) $resource['id'] ?>" data-map-resource="<?= e(array_search((int) $resource['id'], $map_resource_ids, true) ?: '') ?>" <?= $selected === (int) $resource['id'] ? 'checked' : '' ?> required><strong><?= e($resource['name']) ?></strong><span class="badge text-bg-light float-end"><?= e(ucfirst($resource['area_type'])) ?></span><p class="small mt-3 mb-2"><?= e($resource['description']) ?></p><span><?= euro((float) $resource['price_per_slot']) ?> / Slot</span></label><?php endforeach; ?></div><div class="map-panel"><h2 class="h4">Lageplan</h2><p class="small text-secondary">Klicken Sie direkt auf eine Sportanlage im Lageplan.</p><div class="interactive-map" aria-label="Interaktiver Lageplan"><?= file_get_contents(__DIR__ . '/assets/img/sportspot-lageplan.svg') ?></div></div></div><button class="btn btn-primary" type="submit">Datum auswählen</button></form>
<?php require __DIR__ . '/includes/footer.php';