<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/session.php'; require_once __DIR__ . '/includes/helpers.php'; require_once __DIR__ . '/includes/auth.php'; require_once __DIR__ . '/includes/csrf.php'; require_once __DIR__ . '/includes/booking.php';
require_login(); if (empty($_SESSION['booking']['resource_id']) || empty($_SESSION['booking']['booking_date']) || empty($_SESSION['booking']['start_time'])) redirect('booking-step-1.php');
$booking = $_SESSION['booking']; $statement = db()->prepare('SELECT * FROM resources WHERE id = ? AND is_active = 1'); $statement->execute([(int) $booking['resource_id']]); $resource = $statement->fetch(); if (!$resource) redirect('booking-step-1.php'); $extras = booking_extras(); $extra_ids = array_map('intval', (array) ($_POST['extra_ids'] ?? $_SESSION['booking']['extra_ids'] ?? [])); $coupon_code = trim((string) ($_POST['coupon_code'] ?? $_SESSION['booking']['coupon_code'] ?? '')); $calculation = calculate_booking($resource, $extra_ids, $coupon_code);
$coupon_error = $coupon_code !== '' && !$calculation['coupon'] ? 'Der Gutscheincode ist ungültig oder nicht mehr gültig.' : null;
if ($_SERVER['REQUEST_METHOD'] === 'POST') { verify_csrf(); if (isset($_POST['continue'])) { $_SESSION['booking']['extra_ids'] = $extra_ids; $_SESSION['booking']['coupon_code'] = $coupon_code; redirect('booking-summary.php'); } }
$page_title = 'Extras auswählen'; require __DIR__ . '/includes/header.php';
?><p class="step-indicator">Schritt 3 von 4 · <?= e($resource['name']) ?></p><h1>Extras auswählen</h1><form method="post" class="form-panel"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><div class="row g-3 mb-4"><?php foreach ($extras as $extra): ?><div class="col-md-6"><label class="d-block border rounded p-3"><input type="checkbox" name="extra_ids[]" value="<?= (int) $extra['id'] ?>" data-price="<?= e((string) $extra['price']) ?>" <?= in_array((int) $extra['id'], $extra_ids, true) ? 'checked' : '' ?>> <strong><?= e($extra['name']) ?></strong><br><span class="small"><?= e($extra['description']) ?> · <?= euro((float) $extra['price']) ?></span></label></div><?php endforeach; ?></div><div class="mb-3"><label class="form-label" for="coupon_code">Gutscheincode</label><input class="form-control" id="coupon_code" name="coupon_code" value="<?= e($coupon_code) ?>" placeholder="z. B. START10"><div class="form-text">Der Code wird auf der Serverseite geprüft.</div><?php if ($coupon_error): ?><div class="text-danger mt-2" role="alert"><?= e($coupon_error) ?></div><?php endif; ?></div><p class="fw-bold">Zwischensumme: <span data-price-total data-base-price="<?= e((string) $resource['price_per_slot']) ?>"><?= euro((float) $calculation['subtotal']) ?></span></p><button class="btn btn-primary" name="continue" value="1" type="submit">Zusammenfassung anzeigen</button></form>
<?php require __DIR__ . '/includes/footer.php';