<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/session.php'; require_once __DIR__ . '/includes/helpers.php'; require_once __DIR__ . '/includes/auth.php'; require_once __DIR__ . '/includes/csrf.php'; require_once __DIR__ . '/includes/booking.php';
require_login(); if (empty($_SESSION['booking']['resource_id']) || empty($_SESSION['booking']['booking_date']) || empty($_SESSION['booking']['start_times'])) redirect('booking-step-1.php');
$booking = $_SESSION['booking']; $statement = db()->prepare('SELECT * FROM resources WHERE id = ? AND is_active = 1'); $statement->execute([(int) $booking['resource_id']]); $resource = $statement->fetch(); if (!$resource) redirect('booking-step-1.php'); $extras = booking_extras(); $extra_ids_by_slot = (array) ($_POST['extra_ids'] ?? $_SESSION['booking']['extra_ids_by_slot'] ?? []); foreach ($extra_ids_by_slot as $start_time => $extra_ids) $extra_ids_by_slot[$start_time] = array_map('intval', (array) $extra_ids); $coupon_code = trim((string) ($_POST['coupon_code'] ?? $_SESSION['booking']['coupon_code'] ?? '')); $calculation = calculate_slot_bookings($resource, $booking['start_times'], $extra_ids_by_slot, $coupon_code);
$coupon_error = $coupon_code !== '' && !$calculation['coupon'] ? 'Der Gutscheincode ist ungültig oder nicht mehr gültig.' : null;
if ($_SERVER['REQUEST_METHOD'] === 'POST') { verify_csrf(); if (isset($_POST['continue'])) { $_SESSION['booking']['extra_ids_by_slot'] = $extra_ids_by_slot; $_SESSION['booking']['coupon_code'] = $coupon_code; redirect('booking-summary.php'); } }
$page_title = 'Extras auswählen'; require __DIR__ . '/includes/header.php';
?><p class="step-indicator">Schritt 3 von 4 · <?= e($resource['name']) ?></p><h1>Extras pro Zeitslot auswählen</h1><form method="post" class="form-panel"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><?php foreach ($calculation['slots'] as $slot): ?><fieldset class="mb-4"><legend class="h5"><?= e($slot['start_time']) ?> bis <?= e(slot_options()[$slot['start_time']]) ?></legend><div class="row g-3"><?php foreach ($extras as $extra): $slot_extra_ids = $extra_ids_by_slot[$slot['start_time']] ?? []; ?><div class="col-md-6"><label class="d-block border rounded p-3"><input type="checkbox" name="extra_ids[<?= e($slot['start_time']) ?>][]" value="<?= (int) $extra['id'] ?>" <?= in_array((int) $extra['id'], $slot_extra_ids, true) ? 'checked' : '' ?>> <strong><?= e($extra['name']) ?></strong><br><span class="small"><?= e($extra['description']) ?> · <?= euro((float) $extra['price']) ?></span></label></div><?php endforeach; ?></div></fieldset><?php endforeach; ?><div class="mb-3"><label class="form-label" for="coupon_code">Gutscheincode</label><input class="form-control" id="coupon_code" name="coupon_code" value="<?= e($coupon_code) ?>" placeholder="z. B. START10"><div class="form-text">Der Code wird einmal auf die gesamte Buchung angewendet.</div><?php if ($coupon_error): ?><div class="text-danger mt-2" role="alert"><?= e($coupon_error) ?></div><?php endif; ?></div><p class="fw-bold">Gesamtsumme: <?= euro($calculation['total']) ?></p><button class="btn btn-primary" name="continue" value="1" type="submit">Zusammenfassung anzeigen</button></form>
<?php require __DIR__ . '/includes/footer.php';