<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/session.php'; require_once __DIR__ . '/includes/helpers.php'; require_once __DIR__ . '/includes/auth.php'; require_once __DIR__ . '/includes/database.php'; require_once __DIR__ . '/includes/csrf.php'; require_login();
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
	verify_csrf();
	$booking_id = (int) ($_POST['booking_id'] ?? 0);
	$cancel = db()->prepare('UPDATE bookings SET status = "cancelled" WHERE id = ? AND user_id = ? AND status = "confirmed" AND (booking_date > CURRENT_DATE OR (booking_date = CURRENT_DATE AND start_time > CURRENT_TIME))');
	$cancel->execute([$booking_id, (int) current_user()['id']]);
	flash($cancel->rowCount() === 1 ? 'success' : 'danger', $cancel->rowCount() === 1 ? 'Die Buchung wurde storniert.' : 'Die Buchung kann nicht mehr storniert werden.');
	redirect('my-bookings.php');
}
$statement = db()->prepare('SELECT b.*, r.name AS resource_name, GROUP_CONCAT(e.name ORDER BY e.name SEPARATOR ", ") AS extra_names FROM bookings b JOIN resources r ON r.id = b.resource_id LEFT JOIN booking_extras be ON be.booking_id = b.id LEFT JOIN extras e ON e.id = be.extra_id WHERE b.user_id = ? GROUP BY b.id ORDER BY b.booking_date DESC, b.start_time DESC'); $statement->execute([(int) current_user()['id']]); $bookings = $statement->fetchAll(); $page_title = 'Meine Buchungen'; require __DIR__ . '/includes/header.php';
?><h1>Meine Buchungen</h1><p class="lead">Hier sehen Sie ausschließlich Ihre eigenen Buchungen.</p><?php if (!$bookings): ?><div class="alert alert-info">Noch keine Buchungen vorhanden.</div><?php else: ?><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Anlage</th><th>Datum</th><th>Uhrzeit</th><th>Extras</th><th>Status</th><th>Gesamt</th><th>Aktion</th></tr></thead><tbody><?php foreach ($bookings as $booking): $can_cancel = $booking['status'] === 'confirmed' && ($booking['booking_date'] > date('Y-m-d') || ($booking['booking_date'] === date('Y-m-d') && $booking['start_time'] > date('H:i:s'))); ?><tr><td><?= e($booking['resource_name']) ?></td><td><?= e($booking['booking_date']) ?></td><td><?= e(substr($booking['start_time'], 0, 5)) ?>–<?= e(substr($booking['end_time'], 0, 5)) ?></td><td><?= e($booking['extra_names'] ?: 'Keine') ?></td><td><span class="badge <?= $booking['status'] === 'confirmed' ? 'text-bg-success' : 'text-bg-secondary' ?>"><?= e($booking['status'] === 'confirmed' ? 'Bestätigt' : 'Storniert') ?></span></td><td><?= euro((float) $booking['total_price']) ?></td><td><?php if ($can_cancel): ?><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="booking_id" value="<?= (int) $booking['id'] ?>"><button class="btn btn-outline-danger btn-sm" type="submit">Stornieren</button></form><?php else: ?>-<?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
<?php require __DIR__ . '/includes/footer.php';